version: '3'
services:
  # app:
  #   build:
  #     context: ./docker/app
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - .:/app
  #   command: [sh, -c, yarn install && yarn dev]
  #   environment: 
  #     - NODE_ENV=development
  #   depends_on: 
  #     - db
  db:
    image: mongo
    ports:
      - "27017:27017"